include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/firebase_options.dart]
linter:
  rules:
    sort_pub_dependencies: false